name: 'dco-check'
description: 'A GitHub Action that verifies commits in pull-request all include Developer Certificate of Origin (DCO) information'
inputs:
  commits:
    description: 'commits in json format'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
